# Generated by Django 3.1 on 2020-08-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='movie',
            new_name='post',
        ),
    ]
