# Generated by Django 3.1 on 2020-08-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200818_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='movie',
        ),
    ]
